version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.2
    - 2.18.3
    - 2.18.4
    - 2.18.5
  - dependency-name: predis/predis
    versions:
    - 1.1.7
  - dependency-name: vimeo/psalm
    versions:
    - 4.4.1
    - 4.5.0
    - 4.5.1
    - 4.5.2
    - 4.6.0
    - 4.6.1
    - 4.6.2
    - 4.6.3
    - 4.6.4
    - 4.7.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
    - 9.5.4
  - dependency-name: nesbot/carbon
    versions:
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.46.0
  - dependency-name: brainmaestro/composer-git-hooks
    versions:
    - 2.8.4
    - 2.8.5
  - dependency-name: comcast/php-legal-licenses
    versions:
    - 1.1.6
  - dependency-name: nyholm/psr7
    versions:
    - 1.4.0
