preset: symfony

finder:
  exclude:
    - "tests"
    - "vendor"

enabled:
  - not_operator_with_successor_space
  - linebreak_after_opening_tag
  - length_ordered_imports
  - phpdoc_order
  - short_list_syntax
  - short_array_syntax

disabled:
  - phpdoc_no_empty_return
  - yoda_style
  - phpdoc_to_comment
