os:
  - linux

language: php

php:
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  echo '' | pecl install -f redis

before_script:
  - phpenv config-add travis.ini
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload
  - composer validate --no-check-all --strict

script:
  - composer run-script test

after_success:
  - bash <(curl -s https://codecov.io/bash)
