name: Run tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    schedule:
        - cron: '0 0 * * *'
jobs:
    run-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [7.4, 8.0, 8.1, 8.2]

        name: PHP-${{ matrix.php }} - OS-${{ matrix.os }}

        steps:
            - name: Update apt
              run: sudo apt-get update --fix-missing

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: pdo, redis, json
                  coverage: xdebug

            - name: Get composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                  composer self-update
                  composer install --prefer-source --no-interaction
                  composer dump-autoload
                  composer validate --no-check-all --strict

            - name: Execute tests
              run: composer run-script test

            - name: Upload coverage
              uses: codecov/codecov-action@v2
              with:
                  fail_ci_if_error: true
